title: Random file copier
description: This program facilitates copying random Audio/Video files. Random File Copier is also capable of copying random folders. Installation info can be found on the bottom off the page ! So this program can be used to copy random movies and also to copy random MP3 or other music filetypes, even to copy random tv series (here you will use the folder selection)
theme: jekyll-theme-architect
show_downloads: true

