//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RandomFileCopier.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RandomFileCopier.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Audio file types.
        /// </summary>
        public static string AudioFileTypes {
            get {
                return ResourceManager.GetString("AudioFileTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Avoid previous copied.
        /// </summary>
        public static string AvoidPreviousCopied {
            get {
                return ResourceManager.GetString("AvoidPreviousCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This will only work when there were previous copied files copied with this program and whilst the file containing the copied file names has not been deleted.
        /// </summary>
        public static string AvoidPreviousCopiedTooltip {
            get {
                return ResourceManager.GetString("AvoidPreviousCopiedTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse destination.
        /// </summary>
        public static string BrowseDestination {
            get {
                return ResourceManager.GetString("BrowseDestination", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Browse source.
        /// </summary>
        public static string BrowseSource {
            get {
                return ResourceManager.GetString("BrowseSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        public static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Destination path.
        /// </summary>
        public static string DestinationPath {
            get {
                return ResourceManager.GetString("DestinationPath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string FindFiles {
            get {
                return ResourceManager.GetString("FindFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Folders.
        /// </summary>
        public static string FolderFileTypes {
            get {
                return ResourceManager.GetString("FolderFileTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GB.
        /// </summary>
        public static string GB {
            get {
                return ResourceManager.GetString("GB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Include subtitles.
        /// </summary>
        public static string IncludeSubtitles {
            get {
                return ResourceManager.GetString("IncludeSubtitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect directory, the directory should exist and must be well formed.
        /// </summary>
        public static string IncorrectDirectory {
            get {
                return ResourceManager.GetString("IncorrectDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect format, this field should only contain numeric data.
        /// </summary>
        public static string IncorrectDoubleFormat {
            get {
                return ResourceManager.GetString("IncorrectDoubleFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Info.
        /// </summary>
        public static string Info {
            get {
                return ResourceManager.GetString("Info", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected.
        /// </summary>
        public static string IsSelected {
            get {
                return ResourceManager.GetString("IsSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum ({0}).
        /// </summary>
        public static string MaximumFileSize {
            get {
                return ResourceManager.GetString("MaximumFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MB.
        /// </summary>
        public static string MB {
            get {
                return ResourceManager.GetString("MB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum ({0}).
        /// </summary>
        public static string MinimumFileSize {
            get {
                return ResourceManager.GetString("MinimumFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not write/update the file that keeps track of previous copied files!.
        /// </summary>
        public static string NoCopiedFileListFileWritten {
            get {
                return ResourceManager.GetString("NoCopiedFileListFileWritten", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only videos with subtitles.
        /// </summary>
        public static string OnlyVideosWithSubtitles {
            get {
                return ResourceManager.GetString("OnlyVideosWithSubtitles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Folder in File Explorer.
        /// </summary>
        public static string OpenFolder {
            get {
                return ResourceManager.GetString("OpenFolder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Path.
        /// </summary>
        public static string Path {
            get {
                return ResourceManager.GetString("Path", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait.....
        /// </summary>
        public static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copying {0}/{1}.
        /// </summary>
        public static string ProcessingFiles {
            get {
                return ResourceManager.GetString("ProcessingFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search options.
        /// </summary>
        public static string SearchOptions {
            get {
                return ResourceManager.GetString("SearchOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search in subdirectories.
        /// </summary>
        public static string SearchSubDirectories {
            get {
                return ResourceManager.GetString("SearchSubDirectories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selection options.
        /// </summary>
        public static string SelectionOptions {
            get {
                return ResourceManager.GetString("SelectionOptions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size in GB.
        /// </summary>
        public static string SizeInGB {
            get {
                return ResourceManager.GetString("SizeInGB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size in MB.
        /// </summary>
        public static string SizeInMB {
            get {
                return ResourceManager.GetString("SizeInMB", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Some files have not been copied! Make sure the device has not been removed and that the program is being run with the right permission..
        /// </summary>
        public static string SomeFilesHaveNotBeenCopied {
            get {
                return ResourceManager.GetString("SomeFilesHaveNotBeenCopied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Woops! Something went wrong....
        /// </summary>
        public static string SomethingWentWrong {
            get {
                return ResourceManager.GetString("SomethingWentWrong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source path.
        /// </summary>
        public static string SourcePath {
            get {
                return ResourceManager.GetString("SourcePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start Copy.
        /// </summary>
        public static string StartCopy {
            get {
                return ResourceManager.GetString("StartCopy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subtitle Path.
        /// </summary>
        public static string SubtitlePath {
            get {
                return ResourceManager.GetString("SubtitlePath", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All files have been sucessfully copied!.
        /// </summary>
        public static string Success {
            get {
                return ResourceManager.GetString("Success", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Random File Copier.
        /// </summary>
        public static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of files found: {0}.
        /// </summary>
        public static string TotalFilesFound {
            get {
                return ResourceManager.GetString("TotalFilesFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number of files selected: {0}.
        /// </summary>
        public static string TotalFilesSelected {
            get {
                return ResourceManager.GetString("TotalFilesSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total selected filesize: {0:F2} GB.
        /// </summary>
        public static string TotalSelectedSize {
            get {
                return ResourceManager.GetString("TotalSelectedSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video file types.
        /// </summary>
        public static string VideoFileTypes {
            get {
                return ResourceManager.GetString("VideoFileTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warning {
            get {
                return ResourceManager.GetString("Warning", resourceCulture);
            }
        }
    }
}
